urdf_path: ~/.skrobot/pr2_description/pr2.urdf
optimization_frame: base_link # currently unused
control_joint_names: [
    # Note that we do not use torso
    r_shoulder_pan_joint, 
    r_shoulder_lift_joint,
    r_upper_arm_roll_joint,
    r_elbow_flex_joint,
    r_forearm_roll_joint,
    r_wrist_flex_joint, 
    r_wrist_roll_joint]
endeffector_link_name: r_gripper_tool_frame
optframe_xyz_from_ef: [0.0, 0.0, 0.6]
optframe_rpy_from_ef: [0.0, 0.0, 0.0]
