name: Main

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            ros-env:
              # Don't test on noetic because pr2eus is not released
              - ROS_DISTRO: melodic
                UPSTREAM_WORKSPACE: 'yamaopt.rosinstall'
                ROSDEP_SKIP_KEYS: 'fetcheus'
        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Install APT On Linux # This step for just installing skrobot on py 2x...
              run: |
                sudo apt-get update -qq -y
                sudo apt-get install -qq -y libspatialindex-dev freeglut3-dev libsuitesparse-dev libblas-dev liblapack-dev

            - name: Setup ROS
              uses: 'ros-industrial/industrial_ci@master'
              env: ${{matrix.ros-env}}
