name: Main

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            ros-env:
              # (Currently) Don't test on noetic because pr2eus is not released
              - ROS_DISTRO: melodic
                # Use download_sample_data.py with linked devel-space layout (with sourced workspace packages)
                # https://github.com/ros-industrial/industrial_ci/pull/757
                BUILDER: catkin_tools_devel
                # Install GLIBCXX_3.4.26 to use tinyfk (Maybe not needed in noetic)
                # Use ppa repository via custom commands because default industrial_ci does not support it
                # https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#customize-within-the-ci-process
                AFTER_INIT: |
                    # Do not use add-apt-repository command to avoid heavy install of software-properties-common
                    # https://www.usagi1975.com/2019152355/
                    apt-key adv --keyserver keyserver.ubuntu.com --recv 60C317803A41BA51845E371A1E9377A2BA9EF27F
                    echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic main " > /etc/apt/sources.list.d/glibcxx.list
                    deb-src "http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic main" >> /etc/apt/sources.list.d/glibcxx.list
                    apt update -qq
                    apt -qq install -y gcc-9 libstdc++
                # UPSTREAM_WORKSPACE is not needed for melodic (maybe needed for noetic)
                # UPSTREAM_WORKSPACE: 'yamaopt.rosinstall'
                ADDITIONAL_DEBS: |
                    # Installing skrobot on Python 2.x
                    libspatialindex-dev freeglut3-dev libsuitesparse-dev libblas-dev liblapack-dev
                ROSDEP_SKIP_KEYS: 'fetcheus'

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                submodules: recursive # Checkout yamaopt as git submodule

            - name: Cache ros data
              uses: actions/cache@v2
              env:
                # You can discard old cache and use new data by updating version number
                cache-version: v1
              with:
                # rosbag data is installed at ~/.ros/data
                path: ~/.ros/data
                key: cache-ros-data-${{ env.cache-version }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  cache-ros-data-${{ env.cache-version }}

            - name: Setup ROS
              uses: 'ros-industrial/industrial_ci@master'
              env: ${{matrix.ros-env}}
