name: Main

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            ros-env:
              # Don't test on noetic because pr2eus is not released
              - ROS_DISTRO: melodic
                # UPSTREAM_WORKSPACE: 'yamaopt.rosinstall' # Currently not needed
                ROSDEP_SKIP_KEYS: 'fetcheus'
        steps:
            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: 2.7
            - name: Install APT On Linux # This step for just installing skrobot on py 2x...
              run: |
                sudo add-apt-repository ppa:ubuntu-toolchain-r/test
                sudo apt-get update -qq -y
                sudo apt-get install -qq -y libspatialindex-dev freeglut3-dev libsuitesparse-dev libblas-dev liblapack-dev
                sudo apt install -qq -y gcc-9 libstdc++6
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                submodules: recursive # Checkout yamaopt as git submodule
            - name: Setup ROS
              uses: 'ros-industrial/industrial_ci@master'
              env: ${{matrix.ros-env}}
