name: Main

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            ros-env:
              # (Currently) Don't test on noetic because pr2eus is not released
              - ROS_DISTRO: melodic
                # Use download_sample_data.py with workspace packages
                # https://github.com/ros-industrial/industrial_ci/pull/757
                BUILDER: catkin_tools_devel
                # UPSTREAM_WORKSPACE is currently not needed
                # UPSTREAM_WORKSPACE: 'yamaopt.rosinstall'
                # This step for just installing skrobot on py 2x...
                ADDITIONAL_DEBS: 'libspatialindex-dev freeglut3-dev libsuitesparse-dev libblas-dev liblapack-dev'
                ROSDEP_SKIP_KEYS: 'fetcheus'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                submodules: recursive # Checkout yamaopt as git submodule

            - name: Cache ros data
              uses: actions/cache@v2
              env:
                # You can discard old cache and use new data by updating version number
                cache-version: v1
              with:
                # rosbag data is installed at ~/.ros/data
                path: ~/.ros/data
                key: cache-ros-data-${{ env.cache-version }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  cache-ros-data-${{ env.cache-version }}

            - name: Setup ROS
              uses: 'ros-industrial/industrial_ci@master'
              env: ${{matrix.ros-env}}
